import './fonts.css';

import {
  Amsterdam,
  Barrio,
  ChelseaMarket,
  Collage,
  GlassAntiqua,
  GomariceOldBook,
  ItsaSketch,
  Koulen,
  LuckiestGuy,
  Miniver,
  Naive,
  PaletteMosaic,
  Paperland,
  PicoPop,
  PoorStory,
  Poppins,
  SingleDay,
} from './IconsFonts';

export default [
  { name: 'Amsterdam', icon: <Amsterdam /> },
  { name: 'Barrio-Regular', icon: <Barrio /> },
  { name: 'ChelseaMarket', icon: <ChelseaMarket /> },
  { name: 'Collage', icon: <Collage /> },
  { name: 'GlassAntiqua', icon: <GlassAntiqua /> },
  { name: 'gomarice_old_book', icon: <GomariceOldBook /> },
  { name: 'ItsaSketch', icon: <ItsaSketch /> },
  { name: 'Koulen', icon: <Koulen /> },
  { name: 'LuckiestGuy', icon: <LuckiestGuy /> },
  { name: 'Miniver', icon: <Miniver /> },
  { name: 'Naive', icon: <Naive /> },
  { name: 'PaletteMosaic', icon: <PaletteMosaic /> },
  { name: 'Paperland', icon: <Paperland /> },
  { name: 'PicoPop', icon: <PicoPop /> },
  { name: 'PoorStory-Regular', icon: <PoorStory /> },
  { name: 'Poppins', icon: <Poppins /> },
  { name: 'SingleDay', icon: <SingleDay /> },
];
