name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '18.14.2'

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

  tsc:
    name: Run Type Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '18.14.2'

      - name: Install dependencies
        run: npm install

      - name: Type checking
        run: tsc
